name: CI/CD para API Ruby on Rails

on:
  push:
    branches:
      - development # Altere para o nome da sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.x # Altere para a versão Ruby que você está usando

    - name: Instalar dependências
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Configurar banco de dados
      run: |
        bundle exec rails db:drop
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rails db:seed
